services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Markocupic\RszAthletenumfrageBundle\Docx\Athletenumfrage: ~

    Markocupic\RszAthletenumfrageBundle\ContaoBackendMaintenance\MaintainModuleAthletenumfrage: ~

